Add checks for errors with update files in -R
* Update directory is more than 10 minutes old
* Update directory is empty; download probably failed

And:

* Emphasis in -C not using -R if no action is needed

diff --git a/fesh/fesh b/fesh/fesh
--- a/fesh/fesh
+++ b/fesh/fesh
@@ -125,7 +125,14 @@ get_latest_tmp() {
         | head -1)
 
     if [[ -z "$tmp" ]]; then
-        fatal "no /tmp/fesh_${sched}_... directory found"
+        echo "No '-C' temporary directory for ${sched} found." >&2
+        echo "Rerun with '-C' to check for any needed updates." >&2
+        exit 1
+    fi
+    if [ -n "$(find "/tmp/$tmp" -mmin +30 -print -quit 2>/dev/null)" ]; then
+        echo "Most recent '-C' temporary directory for ${sched} is more than 30 minutes old." >&2
+        echo "Rerun with '-C' to make a fresh check for updates." >&2
+        exit 1
     fi
     echo "/tmp/$tmp"
 }
@@ -264,10 +271,10 @@ Options:
  -C       check for changed schedule file (and .txt file if previously
           download) on server; if there were any changes, new versions
           are left on /tmp and a hint for how proceed is printed
- -R       update files that were found to be changed with '-C; the
-          latest versions on /tmp are used; for geo, drudg will be run
-          automatically if the .skd file is update or if the drudg output
-          was stale in '-C'
+ -R       Update files that were found to be changed with '-C; the latest
+          versions less than 10 minutes old on /tmp are used; for geo, drudg
+          will be run automatically if the schedule file is updated or if the
+          drudg output was stale when '-C' was used
  -d       drudg schedule with default settings, not supported for vlbeer
           (needs STATION environment variable or -s set with station code)
  -D dc    Use alternate data center; dc=bkg, cddis, opar, or vlbeer. Upper
@@ -312,7 +319,7 @@ The '-C' option allows checking that already downloaded files and drudg output
 are up-to-date. If files need to updated, the '-R' option should be used
 afterward for that. Additionally, messages for some errors recommend ways to
 use '-C'/'-R' for recovering. Other approaches may work better depending on
-you needs, but the recommended ones fit most situations.
+your needs, but the recommended ones fit most situations.
 
 Please see the end of this message about handling optional 'skedf.ctl'
 specified prompting for 'drudg'.
@@ -695,7 +702,8 @@ if [[ -n "$replace_files" ]]; then
     download=
     run_drudg=
     tmp=$(get_latest_tmp)
-    echo "Found temporary directory $tmp" >&2
+    echo "Found '-C' temporary directory $tmp" >&2
+    action=
     if [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
        if [[ -e "$tmp/$sched.vex" ]]; then
            echo "Updating $SCHED_DIR/$sched.vex" >&2
@@ -703,6 +711,7 @@ if [[ -n "$replace_files" ]]; then
            echo -e "\nBEWARE: Any drudg output is older than $SCHED_DIR/$sched.vex."
            echo      "        You should run drudg manually to update any files you need." >&2
            unlink "$tmp/$sched.vex"
+           action=1
        fi
     else
        if [[ -e "$tmp/$run_drudg_file" ]] ; then
@@ -714,19 +723,28 @@ if [[ -n "$replace_files" ]]; then
            run_drudg=1
            force=1
            unlink "$tmp/$run_drudg_file"
+           action=1
        fi
        if [[ -e "$tmp/$sched.skd" ]]; then
            echo "Updating $SCHED_DIR/$sched.skd" >&2
            cp -f "$tmp/$sched.skd" "$SCHED_DIR"
            unlink "$tmp/$sched.skd"
+           action=1
        fi
        if [[ -e "$tmp/$sched.txt" ]]; then
           echo "Updating $SCHED_DIR/$sched.txt" >&2
           cp -f "$tmp/$sched.txt" "$SCHED_DIR"
           unlink "$tmp/$sched.txt"
+          action=1
        fi
     fi
-    rmdir "$tmp"
+    if [[ -n "$action" ]]; then
+       rmdir "$tmp"
+    else
+       echo "No updates were found. Maybe the download for the previous '-C' failed." >&2
+       echo "Rerun with '-C' to make a fresh check for updates." >&2
+       exit 1
+    fi
 fi
 
 if [[ -n "$run_drudg" && -z "$check_new" ]]; then
@@ -888,7 +906,7 @@ if [[ -n "$check_new" ]]; then
     fi
     if [[ -z "$update_needed" && -z "$drudg_needed" ]] ; then
         rmdir $FESH_TEMP_DIR
-        echo -e "\nNo action needed." >&2
+        echo -e "\nNo action needed. Do NOT rerun with '-R'." >&2
     elif [[ "$FESH_DATA_CENTER" =~ vlbeer ]]; then
         if [[ -n "$update_needed" ]]; then
             cat <<EOF >&2
