Add hint for -H if download from vlbeer fails

diff --git a/fesh/fesh b/fesh/fesh
--- a/fesh/fesh
+++ b/fesh/fesh
@@ -44,7 +44,9 @@ download_files() {
         if wget $WGET_VERBOSE "ftp://ftp@vlbeer.ira.inaf.it/vlb_arc/ftp/vlbi_arch/$month/$sched.vex"; then
             echo Done >&2
         else
-            fatal "Downloading $sched.vex failed"
+            echo "Downloading $sched.vex failed" >&2
+            echo "Use -H to try getting a PRELIMINARY schedule (not in .latest) only if you must." >&2
+            exit 1
         fi
         return
     fi
