Improve help hint if no schedule was specified

diff --git a/fesh/fesh b/fesh/fesh
--- a/fesh/fesh
+++ b/fesh/fesh
@@ -542,7 +542,9 @@ done
 shift $((OPTIND - 1))
 
 if [[ $# -eq 0 ]] ; then
-    usage >&2
+    echo "Usage: fesh [options] schedule"
+    echo "A 'schedule' is required."
+    echo "Try 'fesh -h' option for help" >&2
     exit 1
 fi
 
