Add https for cddis download
Includes adding NETRC_DIR environment variable, matching plog.
Comments added to explain hidden *_DIR feature if skedf.ctl parsing fails.
Silenced verbosity of pushd/popd.

diff --git a/fesh/fesh b/fesh/fesh
--- a/fesh/fesh
+++ b/fesh/fesh
@@ -34,12 +34,16 @@ CONTROL_DIR=${CONTROL_DIR:-"${FS_BASE}/control"}
 LOG_DIR=${LOG_DIR:-"${FS_BASE}/log"}
 # check for skedf.ctl
 if [[ -e $CONTROL_DIR/skedf.ctl ]]; then
-    proc_path=$( perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$proc/i     ) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
-    snap_path=$( perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$snap/i     ) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
-    sched_path=$(perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$schedules/i) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
-    PROC_DIR=${PROC_DIR:-"${proc_path}"}
-    SNAP_DIR=${SNAP_DIR:-"${snap_path}"}
-    SCHED_DIR=${SCHED_DIR:-"${sched_path}"}
+    proc_dir=$( perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$proc/i     ) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
+    snap_dir=$( perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$snap/i     ) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
+    sched_dir=$(perl -ne 'END {if(eof) {$_=".";} print;} if(/^\$schedules/i) {while (<>){if(/^\$/) {$_=".";exit;} elsif(/^[ \t]*([^* \t\n].*?)\/*[ \t]*$/) {$_=$1;exit;}}}' <$CONTROL_DIR/skedf.ctl)
+    PROC_DIR=${PROC_DIR:-"${proc_dir}"}
+    SNAP_DIR=${SNAP_DIR:-"${snap_dir}"}
+    SCHED_DIR=${SCHED_DIR:-"${sched_dir}"}
+#do not use the above the three *_DIR environment variables
+#to override what is in skedf.ctl; they can be used to override
+#what is placed in the corresponding *_dir variables if the
+#perl directory extracts get the wrong result
     LIST_DIR=${LIST_DIR:-${SCHED_DIR}}
 else
 # drudg won't run without skedf.ctl, maybe some day it will
@@ -52,6 +56,18 @@ FESH_DATA_CENTER=${FESH_DATA_CENTER:-'cddis'}
 
 FESH_CDDIS_METHOD=${FESH_CDDIS_METHOD:-'ftp-ssl'}
 
+if [[ -z "${NETRC_DIR:-}" ]]; then
+    NETRC_DIR=$HOME
+    CURL_NETRC_FILE_OPTION=
+else
+    CURL_NETRC_FILE_OPTION=" --netrc-file $NETRC_DIR/.netrc"
+fi
+
+fatal(){
+    echo -e "ERROR: fesh:" "$*" >&2
+    exit 1
+}
+
 year=$(date +%Y)
 
 usage() {
@@ -63,7 +79,7 @@ Options:
     -n      Fetch next observation in master schedule
     -d      DRUDG schedule with default settings
             (needs STATION environment variable set to two letter id)
-    -D dc   User alternate data center; dc=bkg, cddis, or opar
+    -D dc   Use alternate data center; dc=bkg, cddis, or opar
             (see more below about setting the default data center)
     -v      Verbose mode, drudg output printed to stdout
     -V      Print version and exit.
@@ -83,17 +99,18 @@ By default fesh gets an observation for the current year, but this can
 be overridden with '-y' option. That option can be used to get a
 schedule for the next year.
 
-The default data center can be changed by setting it in the
-FESH_DATA_CENTER environment variable. Accepted values are bkg,
-cddis, and opar. For example, to make the default bkg, use:
+The default data center is CDDIS but can be changed by setting the
+FESH_DATA_CENTER environment variable. Accepted values are bkg, cddis,
+and opar. For example, to make the default bkg, use:
 
     setenv FESH_DATA_CENTER bkg #in ~/.login for tcsh or
     export FESH_DATA_CENTER=bkg #in ~/.profile for bash
 
-The '-D' option can be used to specify an alternate data center.
+The '-D' option can be used to specify an alternate data center when
+running the script.
 
 fesh (curl actually) will prompt for an email to use as the password
-for anonymous ftp-ssl access for cddis. This can be suppressed by
+for anonymous ftp-ssl access for CDDIS. This can be suppressed by
 setting a working email address in the FESH_EMAIL variable, e.g.:
 
     setenv FESH_EMAIL user@address #in ~/.login for tcsh or
@@ -107,10 +124,33 @@ variable. For example to make it the current directory, use:
     setenv LIST_DIR . #in ~/.login for tcsh or
     export LIST_DIR=. #in ~/.profile for bash
 
-If you have FSL8 or other old distribution that does not support
-curl ftp-ssl to CDDIS, but worked with the previous versions of
-fesh that used wget for non-ssl ftp, you can restore the previous
-behaviour with:
+The default transfer method from CDDIS is ftp-ssl.  You can use https
+as the method with CDDIS if you set:
+
+    setenv FESH_CDDIS_METHOD https #in ~/.login for tcsh or
+    export FESH_CDDIS_METHOD=https #in ~/.profile for bash
+
+For the CDDIS https method, the login must be configured in ".netrc"
+which by default is in "~".  For example:
+
+    machine urs.earthdata.nasa.gov
+        login mycddisuser
+        password secret
+
+If your curl supports the "--netrc-file" option (see "man curl") , you
+can change the directory used for ".netrc" by setting the NETRC_DIR
+environment variable.  The matches plog. E.g., add the following to
+your login script
+
+    setenv NETRC_DIR "/usr2/control" #in ~/.login for tcsh or
+    export NETRC_DIR="/usr2/control" #in ~/.profile for bash
+
+See "man 5 netrc" for more details on ".netrc".
+
+If you have FSL8 or another old distribution that does not support
+curl ftp-ssl or https with CDDIS, but worked with the previous
+versions of fesh that used wget for non-ssl ftp, you can restore the
+previous behaviour with:
 
     setenv FESH_CDDIS_METHOD ftp #in ~/.login for tcsh or
     export FESH_CDDIS_METHOD=ftp #in ~/.profile for bash
@@ -175,7 +215,7 @@ if [[ ! "$FESH_DATA_CENTER" =~ ^(cddis|opar|bkg)$ ]]; then
    exit 1
 fi
 
-if [[ ! "$FESH_CDDIS_METHOD" =~ ^(ftp|ftp-ssl)$ ]]; then
+if [[ ! "$FESH_CDDIS_METHOD" =~ ^(ftp|ftp-ssl|https)$ ]]; then
    echo "Unknown cddis method: $FESH_CDDIS_METHOD."
    exit 1
 fi
@@ -221,13 +261,24 @@ if [[ -z "${FESH_EMAIL:-}" ]]; then
 else
     user="anonymous:$FESH_EMAIL"
 fi
-pushd "$SCHED_DIR"
+pushd "$SCHED_DIR" >/dev/null
 version
 echo Fetching schedule from server...
 #TODO: if not found, maybe check next or previous years?
 if [[ "$FESH_DATA_CENTER" =~ cddis ]]; then
     if [[ "$FESH_CDDIS_METHOD" =~ ^ftp$ ]]; then
         wget -nv --backups=1 "ftp://cddis.gsfc.nasa.gov/vlbi/ivsdata/aux/$year/$sched/$sched.skd"
+    elif [[ "$FESH_CDDIS_METHOD" =~ ^https$ ]]; then
+        if [[ ! -e "$NETRC_DIR/.netrc" ]]; then
+            fatal "$NETRC_DIR/.netrc not found, see usage"
+        fi
+
+        if ! grep -q urs.earthdata.nasa.gov "$NETRC_DIR/.netrc"; then
+            fatal "$NETRC_DIR/.netrc does not contain CDDIS login information, see usage"
+        fi
+        curl  -k  -c ~/.urs_cookies -n \
+            $CURL_NETRC_FILE_OPTION \
+            -L -O "https://cddis.nasa.gov/archive/vlbi/ivsdata/aux/$year/$sched/$sched.skd"
     else
         curl -u "$user" -O --ftp-ssl "ftp://gdc.cddis.eosdis.nasa.gov/vlbi/ivsdata/aux/$year/$sched/$sched.skd"
     fi
@@ -237,7 +288,7 @@ elif [[ "$FESH_DATA_CENTER" =~ bkg ]]; then
 wget -nv --backups=1 "ftp://ivs.bkg.bund.de/pub/vlbi/ivsdata/aux/$year/$sched/$sched.skd"
 fi
 echo Done
-popd
+popd >/dev/null
 
 drudg_out="/dev/null"
 if [[ -n "$verbose" ]]; then
