Use a created temporary directory in plog
This is in place of just using /tmp. This removes the prohibition of
having files on /tmp. The temporary directory name is of the form
/tmp/plog_XXX, created with mktemp. One directory is created for each
run of plog. This, in principle, allows running more than one instance
of plog at a time, but that has not been tested.

diff --git a/plog/plog b/plog/plog
--- a/plog/plog
+++ b/plog/plog
@@ -20,7 +20,7 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
-VERSION=2025-12-07
+VERSION=2025-12-10
 
 version(){
     echo "[plog $VERSION]"
@@ -47,6 +47,9 @@ PLOG_REDACT_REPLACEMENT_STRING="${PLOG_REDACT_REPLACEMENT_STRING:-IP_ADDR_REDACT
 # Added to filename before extension of log files with all data
 PLOG_FULL_SUFFIX="${PLOG_FULL_SUFFIX:-_full}"
 
+#initially empty
+PLOG_TEMP_DIR=
+
 usage_long() {
     cat <<EOF
 Push logs and files to the data centers with IP addresses redacted.
@@ -60,8 +63,12 @@ multicast data) and a compressed '_full' log (with multicast data included).
 Both have IP addresses redacted unless the '-D' option is used.  For a path,
 or a procedure file when using '-p', only redaction is available.  If '-p' is
 used, a compressed procedure file will be ignored (but can be pushed as a
-path).  Other logs and files may already be compressed.  If redaction is
-needed, the log or file must not be at the top-level of '/tmp'.
+path).  Other logs and files may already be compressed.
+
+Except to rename a log with multicast data to include '_full' in the name, if
+not already present, none of the original files are modified.  For each run of
+$(basename $0) that needs to create modified files, a directory of the form
+/tmp/$(basename $0)_XXX will be created to hold them.
 
 ${underline}Options:${normal}
     ${black}-l${normal}            Add the experiment ID for the latest log in
@@ -98,13 +105,13 @@ For an experiment ID, if the log contains RDBE or DBBC3 multicast data:
     before '.log'.
 
 2.  If neither '-r' or '-z' is supplied both a reduced log and a compressed
-    full log will be created on /tmp and uploaded.
+    full log will be created in the temporary directory and uploaded.
 
 3.  If '-r' is supplied, only a reduced log file, without multicast data,
-    created in /tmp and is transferred to the data center.
+    created in the temporary directory and transferred to the data center.
 
-4.  If '-z' is supplied, only a compressed full log file is created in /tmp
-    and transferred to the data center.
+4.  If '-z' is supplied, only a compressed full log file is created in the
+    temporary directory and transferred to the data center.
 
 For experiment IDs, the STATION environment variable must be set to the
 two-letter station code. Upper and lower case values are accepted, but they
@@ -145,8 +152,8 @@ four-octet decimal IPv4 addresses from the files pushed. Both false positives
 and negatives are possible. The -e' option can be used to display the strings
 that will be redacted (add '-T' to preview without pushing any files). The
 addresses will be replaced with the string 'IP_ADDR_REDACTED_BY_PLOG'. The
-original files will not be altered. If a file will be redacted, it must not be
-at the top-level of '/tmp'. For a path, unless '-D' is used, if the file has a
+modified file will be created in the temporary directory. The original files
+will not be altered. For a path, unless '-D' is used, if the file has a
 different compression than is selected (gzip instead of bzip2, or vice-versa)
 the file will be rejected; files with other compression types (e.g., xz), will
 be uploaded without redaction, which is probably not what is wanted.
@@ -154,7 +161,6 @@ be uploaded without redaction, which is probably not what is wanted.
 For experiment IDs, 'plog' looks in the log directory, usually /usr2/log (and
 for procedure files, /usr2/proc). You can specify a different directory with
 the FS_LOG_PATH environment variable (and for procedure files, FS_PROC_PATH).
-If redaction is needed, the directory must not be '/tmp'.
 
 plog defaults to using bzip2 compression, if it is available, for full log
 files. Otherwise gzip is used. The use of gzip can be forced with the command
@@ -232,6 +238,12 @@ EOF
 fatal(){
     echo -e "${red}ERROR:${normal} plog:" "$*" >&2
     exit 1
+}
+
+# fatal that works in a sub shell by using kill 0
+fatalk(){
+    echo -e "${red}ERROR:${normal} plog:" "$*" >&2
+    kill 0
 }
 
 warn(){
@@ -454,7 +466,11 @@ compress() {
 
     local ext=${1#*.}
     local name=$(basename "$1")
-    local out="/tmp/$name.$PLOG_COMPRESSED_EXT"
+
+    if [[ "$PLOG_TEMP_DIR" == "" ]]; then
+        fatalk  "Programming error: temporary directory not defined"
+    fi
+    local out="$PLOG_TEMP_DIR/$name.$PLOG_COMPRESSED_EXT"
 
     info Creating compressed file $out ...
     if [[ -n "$DRY" ]]; then
@@ -467,7 +483,11 @@ compress() {
 # Uncompress the log to a temp directory
 uncompress() {
     local name=$(basename $1 .$PLOG_COMPRESSED_EXT)
-    local out="/tmp/$name"
+
+    if [[ "$PLOG_TEMP_DIR" == "" ]]; then
+        fatalk  "Programming error: temporary directory not defined"
+    fi
+    local out="$PLOG_TEMP_DIR/$name"
 
     if [[ "$PLOG_COMPRESSED_EXT" =~ bz2 ]]; then
         local uncompress_program=bunzip2
@@ -483,11 +503,16 @@ uncompress() {
     fi
     echo "$out"
 }
-# Return a reduced log in /tmp can either be raw or compressed log
+# Return a reduced log in $PLOG_TEMP_DIR, can either be raw or compressed log
 reduce() {
     local ext=${1#*.}
     local name=$(basename $(basename "$1" .$ext) $PLOG_FULL_SUFFIX)
-    local out="/tmp/$name.log"
+
+    if [[ "$PLOG_TEMP_DIR" == "" ]]; then
+        fatalk  "Programming error: temporary directory not defined"
+    fi
+    local out="$PLOG_TEMP_DIR/$name.log"
+
     info Creating reduced file $out ...
     if [[ "$PLOG_COMPRESSED_EXT" == bz2 && ${1##*.} != bz2 ]]; then
 # bunzip2 (via bzegrep) doesn't pass the first 5000 bytes of an uncompressed
@@ -520,21 +545,21 @@ else
     echo ""
 fi
 }
-#used if redacting to make sure file is not at the top level of /tmp
+# create temporary directory if needed
 check_tmp() {
-local path=$(realpath -m -- "$1" || fatal "Using realpath to check file path failed")
-if [[ "$path" == "" ]]; then
-    fatal "Checking file path failed"
+if [[ -n "$DRY" ]]; then
+    PLOG_TEMP_DIR="/tmp"
+    return
+elif [[ "$PLOG_TEMP_DIR" == "" ]]; then
+    PLOG_TEMP_DIR=$(mktemp -d  "/tmp/$(basename $0)_XXX" || fatal "Using mktemp to create temporary directory failed." )
+    if [[ "$PLOG_TEMP_DIR" == "" ]]; then
+        fatal "Creating temporary directory failed"
+    fi
+    info "Created temporary directory $PLOG_TEMP_DIR"
 fi
-if [[ $(dirname -- "$path") == "/tmp" ]]; then
-  fatal "$path is in the top-level of /tmp"
-  fi
 }
 # Return redacted file in /tmp must be uncompressed file
 redact() {
-    local name=$(basename "$1" .tmp)
-    local out="/tmp/$name"
-
     if [[ -n "$PRINT_IPS" ]]; then
         info Creating redacted string list ...
         if [[ -n "$DRY" ]]; then
@@ -543,6 +568,13 @@ redact() {
             safe_pv "$1" | perl -nE 'while (/\b(?:\d{1,3}\.){3}\d{1,3}\b/g) { say $& }' | sort -u >&2
         fi
     fi
+
+    local name=$(basename "$1" .tmp)
+
+    if [[ "$PLOG_TEMP_DIR" == "" ]]; then
+        fatalk  "Programming error: temporary directory not defined"
+    fi
+    local out="$PLOG_TEMP_DIR/$name"
 
     info Creating redacted file $out ...
     if [[ -n "$DRY" ]]; then
@@ -736,7 +768,7 @@ main () {
                 add $ref
                 continue
             fi
-            check_tmp $ref
+            check_tmp
             if [[ ${ref##*.} == $PLOG_COMPRESSED_EXT ]]; then
                 uncompressed_file=$(uncompress $ref)
                 $DRY mv $uncompressed_file "$uncompressed_file.tmp"
@@ -764,7 +796,7 @@ main () {
             if [[ -z "$REDACT" ]]; then
                 add $proc
             else
-                check_tmp $proc
+                check_tmp
                 add $(redact $proc)
             fi
         fi
@@ -795,11 +827,6 @@ main () {
         # If log contains IP address data, it will need to be redacted
         REDACT=$(check_ip $log)
 
-        #check not at top of /tmp for redacting
-        if [[ -n "$REDACT" ]]; then
-            check_tmp $log
-        fi
-
         # If log contains multicast data, rename to _full.* since we will upload a reduced file
         FULL=
         infon Checking for multicast data ...
@@ -824,9 +851,15 @@ main () {
         # If given '-z' command, compressed file, add it to the queue, and move on
         if [[ -n "$COMPRESS" ]]; then
             if [[ -z "$REDACT" ]]; then
+                if [[ $log =~ $PLOG_COMPRESSED_EXT$ ]]; then
+                    add $log
+                    continue
+                fi
+                check_tmp
                 add $(compress $log)
                 continue
             fi
+            check_tmp
             if [[ $log =~ $PLOG_COMPRESSED_EXT$ ]]; then
                 uncompressed_file=$(uncompress $log)
                 $DRY mv $uncompressed_file "$uncompressed_file.tmp"
@@ -842,12 +875,14 @@ main () {
             # If log is compressed, extract in a tmp dir upload
             if [[ -z "$REDACT" ]]; then
                 if [[ $log =~ $PLOG_COMPRESSED_EXT$ ]]; then
+                    check_tmp
                     add $(uncompress $log)
                     continue
                 fi
                 add $log
                 continue
             else
+                check_tmp
                 if [[ $log =~ $PLOG_COMPRESSED_EXT$ ]]; then
                     uncompressed_file=$(uncompress $log)
                     $DRY mv $uncompressed_file "$uncompressed_file.tmp"
@@ -861,12 +896,14 @@ main () {
 
         # The log must now contain multicast data, so generate reduced log and add it to the queue
         if [[ -z "$REDACT" ]]; then
+            check_tmp
             add $(reduce $log)
             # If not given '-r' also send a compressed log.
             if [[ -n "$BOTH" ]]; then
                 add $(compress $log)
             fi
         else
+            check_tmp
             if [[ $log =~ $PLOG_COMPRESSED_EXT$ ]]; then
                 uncompressed_file=$(uncompress $log)
                 # for not -r send both
